### ISSUE TITLE
Weird Issue keeps happening

### ISSUE THREAD

**Issue by devcoinfet** [drigg3r/SnCrawler#8]
SnCrawler/crawler.py", line 301, in crawl
    getUrl,getForm,PostForm,getJs = findAllValues(s,url,subdomains,js)#Gets the hrefs, get and post forms
ValueError: need more than 3 values to unpack

This keeps happening when I call the code from the command line as I am using the sub process module to execute your program and have it give me urls back I did it via python code and as a fresh download from github and running it

**Comment by devcoinfet** [comment]
Both cause the issue no matter if I use Your code directly or shell it out

**Comment by ret2jazzy** [comment]
Just merged a PR, it should work now

**Comment by devcoinfet** [comment]
That's fixed but since I am working with you code I need it to get merged like this
I noticed its spamming my console with 

/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings


so my suggested fix below is to set verify SSL to False

def normalizeUrl(url):#Find's if url is accessible with https or not
	if url.startswith("https://") or url.startswith("http://"):
		return url
	try:
		requests.get("https://"+url, timeout=5,verify =False)#
		return "https://"+url
	except:
return "http://"+url
